name: Sync to GitLab

on:
  push:
    branches:
      - main  # Spécifiez la branche que vous voulez synchroniser

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt GitHub (clone complet)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Cloner l'historique complet pour éviter les erreurs de shallow update

      - name: Configurer l'identité Git
        run: |
          git config --global user.email "topdeveloppement@gmail.com"
          git config --global user.name "Omar Kennouche"

      - name: Ajouter le dépôt GitLab comme remote
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/ai-nexus-one-formation/machine-learning.git

      - name: Forcer le push vers GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git push -u gitlab main --force
